### ISSUE TITLE
feat: new landing page

### ISSUE THREAD

**Issue by ayoayco** [ayoayco/Cozy#88]
Move the app into it's own page, so it is accessible in route `'/a'` ... the way to do this is move the current `index.astro` page contents into a new `a.astro` page.

After that you can create the project landing page in a new `index.astro` page :)

Feel free to explore designs you think is aligned to the project: **a modern-day reading assistant**.

**Comment by SoldierCorp** [comment]
Hi @ayoayco 

I would like to contribute to your project. Could you please assign this task to me?

**Comment by ayoayco** [comment]
Sure @SoldierCorp -- let me know if you need help!

**Comment by SoldierCorp** [comment]
I moved the content of `index.astro` to `a.astro` 

What should I put in the `index.astro` instead? Or is that a different task?

<img width="900" alt="image" src="https://github.com/ayoayco/cozy/assets/1775881/a5f8b4cc-f195-4807-ab7c-dce4601296ef">

**Comment by ayoayco** [comment]
The main goal of this issue is a new landing page so that's the content of `index.astro`

**Comment by SoldierCorp** [comment]
Got it! @ayoayco
